import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul className={styles.navlist}>
          <li>
            <Link href="/novembro" className={styles.navlink}>
              Novembro
            </Link>
          </li>
          <li>
            <Link href="/dezembro" className={styles.navlink}>
              Dezembro
            </Link>
          </li>
          <li>
            <Link href="/fevereiro" className={styles.navlink}>
              Fevereiro
            </Link>
          </li>
          <li>
            <Link href="/diadamulher" className={styles.navlink}>
              Dia das mulheres
            </Link>
          </li>
          <li>
            <Link href="/marco" className={styles.navlink}>
              Março
            </Link>
          </li>
        </ul>
      </main>
    </>
  );
}
