import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          src="/images/home-bg.png"
          width={999}
          height={999}
          alt="bg"
          className={styles.image}
          priority="true"
        />
        <div className={styles.navlist}>
          <Link href="/abril" className={styles.navlink}>
            Abril
          </Link>
          <Link href="/marco" className={styles.navlink}>
            Março
          </Link>
          <Link href="/diadamulher" className={styles.navlink}>
            Dia das mulheres
          </Link>
          <Link href="/fevereiro" className={styles.navlink}>
            Fevereiro
          </Link>
          <Link href="/dezembro" className={styles.navlink}>
            Dezembro
          </Link>
          <Link href="/novembro" className={styles.navlink}>
            Novembro
          </Link>
        </div>
      </main>
    </>
  );
}
